---
# tasks file for tomcat-ansible-role

- name: Install Java on RedHat
  yum:
    name: "{{ item.package }}"
    state: present
  with_items: "{{ tomcat_java_packages_RedHat }}"
  when: tomcat_install_java and ansible_os_family=='RedHat'

- name: Install Java on Debian
  apt:
    name: "{{ item.package }}"
    state: present
  with_items: "{{ tomcat_java_packages_Debian }}"
  when: tomcat_install_java and ansible_os_family=='Debian'

- name: Check if tomcat is already installed
  stat:
    path: "{{ tomcat_install_path }}/KovairDevOps/apache-tomcat-{{ tomcat_version }}"
  register: is_tomcat_installed

- name: Create tomcat installation directory
  file:
    path: '{{ tomcat_install_path }}/KovairDevOps'
    state: directory
  when: not is_tomcat_installed.stat.exists

- name: Create temp directory
  file:
    path: '{{ tomcat_temp_download_path }}'
    state: directory
  changed_when: false
  when: not is_tomcat_installed.stat.exists

- name: Download apache-tomcat-{{ tomcat_version }}.tar.gz
  get_url:
    url: "{{ tomcat_downloadURL }}/tomcat/tomcat-{{ tomcat_version.split('.')[0] }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: '{{ tomcat_temp_download_path }}'
    timeout: 120
  when: not is_tomcat_installed.stat.exists

- name: Unarchive apache-tomcat-{{ tomcat_version }}.tar.gz at {{ tomcat_install_path }}/KovairDevOps
  unarchive:
    src: "{{ tomcat_temp_download_path }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_install_path }}/KovairDevOps"
    remote_src: True
    creates: "{{ tomcat_install_path }}/KovairDevOps/apache-tomcat-{{ tomcat_version }}"
  when: not is_tomcat_installed.stat.exists
  register: tomcat_installed

- name: Remove all directory from webapps folder
  file:
    path: "{{ tomcat_install_path }}/KovairDevOps/apache-tomcat-{{ tomcat_version }}/webapps/*"
    state: absent
  when: not is_tomcat_installed.stat.exists

- name: Clean up temporary files
  file:
    path: "{{ tomcat_temp_download_path }}"
    state: absent
  changed_when: false
  when: not is_tomcat_installed.stat.exists

- name: Create group {{ tomcat_group }}
  group:
    name: "{{ tomcat_group }}"
    state: present

- name: Create user {{ tomcat_user }}
  user:
    name: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    state: present
    home: "{{ tomcat_install_path }}/KovairDevOps/apache-tomcat-{{ tomcat_version }}"
