---
# tasks file for kovairdevops-ansible-role

- name: Copy Certificate KeyStoreFile at tomcat directory
  copy:
    src: "{{ certificate_keystore_file }}"
    dest: "{{ tomcat_install_path }}/KovairDevOps/apache-tomcat-{{ tomcat_version }}/"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  notify: restart tomcat

- name: Instance Details
  debug:
    msg:
      - "Instance URL: https://{{ url_value }}.devops.kovair.com"
      - "Application username/password: admin/admin"