---
# tasks file for kovairdevops-ansible-role

- name: Disable default agent for SCM, Build, Deploy, Test and CustomCommand plugins
  community.mysql.mysql_query:
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    login_db: "{{ database }}"
    query:
      - UPDATE tplugin SET nodefaultagent = 'Y' WHERE plugincategoryid IN (1,2,3,4) OR toolname = 'CustomCommand';
  no_log: true
