---
# defaults file for tomcat-ansible-role

tomcat_state: present

tomcat_version: 8.5.78

cloud_platform: aws

tomcat_install_java: true
tomcat_java_version: 1.8
tomcat_java_home_redhat: /usr/lib/jvm/jre
tomcat_java_home_debian: /usr/lib/jvm/java-8-openjdk-amd64/jre

tomcat_java_packages_RedHat:
 - {package: "java-{{ tomcat_java_version }}{% if '1.' in tomcat_java_version|string %}.0{% endif %}-openjdk"}
 
tomcat_java_packages_Debian:
 - {package: "openjdk-{{ tomcat_version.split('.')[0] }}-jdk"}

tomcat_downloadURL: https://archive.apache.org/dist

tomcat_user: tomcat
tomcat_group: tomcat

tomcat_user_service: tomcat
tomcat_group_service: tomcat

tomcat_install_path: /opt
tomcat_service_name: tomcat
tomcat_systemd_config_path: /etc/systemd/system
tomcat_jvm_memory_percentage_xms: 15
tomcat_jvm_memory_percentage_xmx: 55

tomcat_webapps_auto_deployment: true
tomcat_permissions_ensure_on_every_run: true

tomcat_allow_manager_access_only_from_localhost: false
tomcat_allow_host_manager_access_only_from_localhost: false

tomcat_debug_mode: false

tomcat_listen_address: 0.0.0.0
tomcat_port_shutdown: 8005
tomcat_port_connector: 8080
tomcat_port_redirect: 8443
tomcat_port_ajp: 8009
tomcat_port_debug: 8000

certificate_keystore_file: "STAR_devops_kovair_com.jks"
certificate_keystore_password: "password"
proxy_name: productiontest

tomcat_ajp_enabled: false
tomcat_ajp_listen_address: "::1"
tomcat_ajp_secret: "my-@jp-s3cr3t"
tomcat_ajp_secret_required: true

tomcat_service_enabled_on_startup: true

tomcat_users: []

tomcat_user_roles: []

tomcat_template_manager_context: "manager-context.xml.j2"
tomcat_template_host_manager_context: "host-manager-context.xml.j2"
tomcat_template_systemd_service: "tomcat.service.j2"
tomcat_template_setenv_redhat: "tomcat.setenv.redhat.sh.j2"
tomcat_template_setenv_debian: "tomcat.setenv.debian.sh.j2"
tomcat_template_server_aws: "tomcat-server-{{ '.'.join(tomcat_version.split('.')[:2]) }}.xml_aws.j2"
tomcat_template_server_azure: "tomcat-server-{{ '.'.join(tomcat_version.split('.')[:2]) }}.xml_azure.j2"
tomcat_template_web: "tomcat-web-{{ '.'.join(tomcat_version.split('.')[:2]) }}.xml.j2"
tomcat_template_users: "tomcat-users-{{ '.'.join(tomcat_version.split('.')[:2]) }}.xml.j2"

tomcat_temp_download_path: /tmp/ansibletomcattempdir

# Uninstall default parameters
tomcat_uninstall_create_backup: true

tomcat_uninstall_remove_user: true
tomcat_uninstall_remove_group: true
tomcat_uninstall_remove_java: false

tomcat_uninstall_remove_all: false
